### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by tanyapowell** [frocentric/froware-launch-landingpage#11]

**Comment by tanyapowell** [comment]
@okbrown does this issue refer to this button 
![image](https://user-images.githubusercontent.com/11095605/96051471-7ad8f980-0e73-11eb-82a6-b52e4c170300.png) 

or the button in the `Header`?

**Comment by okbrown** [comment]
😄  Yes dear, but long term wise, this could be a collection of them or a base button that gets composed with various icons.
